name: Python Application

on:
  push:
    branches:
      - main

jobs:
  run-python-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Python script
        run: python app.py
